[package]
name = "save-and-execute"
version = "0.2.0"
edition = "2021"

[[bin]]
name = "se"
path = "src/main.rs"

[dependencies]
dirs = "5.0.1"
rustyline = "12.0.0"
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.104"

[build-dependencies]
winres = "0.1.12"
